# Generated by Django 3.2.8 on 2025-06-06 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20250606_0133'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='project_type',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
